name: Sample Workflow
on:
  push:
    branches:
      - main
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: display success message
        run: echo "Welcome to GitHub Actions"
            
