name: Sample Workflow
on:
  push:
    branches:
      - main
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: display success message
        run: echo "Welcome to GitHub Actions"
      - name: display list of files
        run:
          pwd
          ls
      - name: setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'


          
            
