name: Sample Workflow
on:
  push:
    branches:
      - main
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: display success message
        run: echo "Welcome to GitHub Actions"
      - name: display list of files
        run:
          ls
      - name: setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: maven command
        run: mvn package
      - name: display the folder content post maven excution
        run: ls
  next-job:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout
        uses: actions/checkout@v4.2.2
  
