name: Secrets
on:
  push:
    branches:
      - main
jobs:
  secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: display secret message
        run: echo ${{secrets.demo}}
